name: Arty-CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build
      - name: submodules
        shell: bash
        run: git submodule sync --recursive && git submodule update --init --force --recursive --depth=1      
      - name: test
        run: cd build && ctest
