name: Arty-CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container: nvidia/opengl:1.0-glvnd-devel-ubuntu18.04
    steps:
      - name: install
        run: apt-get install git
      - uses: actions/checkout@v2
      - name: checkout
        shell: bash
        run: |
            auth_header="$(git config --local --get http.https://github.com/.extraheader)"
            git submodule sync --recursive
            git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1      
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build
      - name: test
        run: cd build && ctest
